port: 9081
#release,debug,test
mode: release
mysql:
  host: "127.0.0.1"
  port: 3306
  user: root
  password: Root_2019
  chart: "utf8mb4"
  db_name: "test"
redis:
  host: "127.0.0.1"
  port: 6379
  user:
  password: